plugins {
     id 'java'
     id 'antlr'
}

description = "The core data structures for KeY for Solidity"

configurations { }

dependencies {
    api project(':key.util')
    api project(':key.ncore')
    api project(':key.ncore.calculus')
    antlr('org.antlr:antlr4:4.13.1')
    implementation 'org.jspecify:jspecify:1.0.0'
    implementation('com.google.code.gson:gson:2.11.0')
    testImplementation(platform('org.junit:junit-bom:5.10.0'))
    testImplementation('org.junit.jupiter:junit-jupiter')

    implementation platform("com.fasterxml.jackson:jackson-bom:2.19.1")
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation 'com.fasterxml.jackson.core:jackson-core:2.19.1'
}



generateGrammarSource {
    arguments += ["-visitor", "-lib" , "../key.ncore/src/main/antlr/"]
}

tasks.withType(Test) {
    enableAssertions = true
}


checkerFramework {
    if(System.getProperty("ENABLE_NULLNESS")) {
        checkers = [
                "org.checkerframework.checker.nullness.NullnessChecker",
        ]
        extraJavacArgs = [
                "-AonlyDefs=^org\\.key_project\\.solidity\\.parser\\.builder",
                "-Xmaxerrs", "10000",
                "-Astubs=$rootDir/key.util/src/main/checkerframework:permit-nullness-assertion-exception.astub",
                "-AstubNoWarnIfNotFound",
                "-Werror",
                "-Aversion",
        ]
    }
}
