/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package org.key_project.solidity.logic.parser;

import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

import org.key_project.logic.Name;
import org.key_project.solidity.logic.ast.SolidityProgramElement;
import org.key_project.solidity.logic.ast.abstractions.Type;
import org.key_project.solidity.logic.ast.declarations.*;
import org.key_project.solidity.logic.ast.expressions.*;
import org.key_project.solidity.logic.ast.expressions.literals.BoolLiteral;
import org.key_project.solidity.logic.ast.expressions.literals.Literal;
import org.key_project.solidity.logic.ast.expressions.literals.Uint256Literal;
import org.key_project.solidity.logic.ast.expressions.operators.AddOperation;
import org.key_project.solidity.logic.ast.expressions.operators.MultiplicationOperation;
import org.key_project.solidity.logic.ast.expressions.operators.SubtractionOperation;
import org.key_project.solidity.logic.ast.references.ParameterVariableReference;
import org.key_project.solidity.logic.ast.references.StateVariableReference;
import org.key_project.solidity.logic.ast.references.TypeReference;
import org.key_project.solidity.logic.ast.references.VariableReference;
import org.key_project.solidity.logic.ast.statement.AssignmentStatement;
import org.key_project.solidity.logic.ast.statement.Block;
import org.key_project.solidity.logic.ast.statement.ReturnStatment;
import org.key_project.solidity.logic.ast.statement.Statement;

import com.fasterxml.jackson.core.io.BigIntegerParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.NonNull;

import static org.key_project.solidity.logic.ast.abstractions.PrimitiveType.BOOL;
import static org.key_project.solidity.logic.ast.abstractions.PrimitiveType.UINT256;

///
/// Parses the JSON representation of a solidity source unit generated by {@code solc} and converts
/// it
/// into a KeY for Solidity AST representation
///
public class SolJSONParser {

    /// keeps track of JSON ids assigned to declarations, required for resolving field references,
    /// types etc.
    /// TODO: what if a type under declaration references itself (is that possible in Solidity?)
    private HashMap<Integer, Declaration> id2Name = new HashMap<>();

    /// parses the Solidity file found at the provided [URI] and converts it into a
    /// list of [SolidityProgramElement]s of declarations representing the Solidity programs
    /// @param file the URI where to find the Solidity code
    /// @return list of top level declarations (usually contracts) representing the Solidity code
    public List<SolidityProgramElement> parse(URI file) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(file.toURL());
        return json2SolidityAST(root);
    }

    /// convert the JSON AST representation into a KeY for Solidity representation
    /// @param root the root node representing the JSON AST
    /// @return the KeY AST representation of {@code root}
    private List<SolidityProgramElement> json2SolidityAST(JsonNode root) {
        if ("SourceUnit".equals(root.findValue("nodeType").asText())) {
            return parseSourceUnit(root.findValues("nodes"));
        }
        return new ArrayList<>();
    }

    private List<SolidityProgramElement> parseSourceUnit(List<JsonNode> nodes) {
        List<SolidityProgramElement> elements = new ArrayList<>();
        for (var node : nodes) {
            if (node.findValue("contractKind").asText().equals("contract")) {
                elements.add(parseContract(node));
            }
        }
        return elements;
    }


    private ContractDeclaration parseContract(JsonNode contractNode) {
        String contractName = contractNode.findValue("canonicalName").asText(); // there is also a
        // field "name"
        // now retrieve declared fields, functions, structs etc.
        List<StateVariableDeclaration> fields = new ArrayList<>();
        List<FunctionDeclaration> functions = new ArrayList<>();

        for (Iterator<JsonNode> it = contractNode.findValue("nodes").elements(); it.hasNext();) {
            final JsonNode node = it.next();
            final String nodeType = node.findValue("nodeType").asText();
            switch (nodeType) {
                case "VariableDeclaration" -> fields.add(parseField(node));
                case "FunctionDefinition" -> functions.add(parseFunction(node));
                default -> throw new RuntimeException("Unknown node type " + nodeType);
            }
        }

        final ContractDeclaration cdecl =
            new ContractDeclaration(new Name(contractName), fields, functions);
        final int contractId = contractNode.findValue("id").asInt();
        id2Name.put(contractId, cdecl);
        return cdecl;
    }

    private FunctionDeclaration parseFunction(JsonNode node) {
        final String name = node.findValue("name").asText();
        List<JsonNode> parameters = node.findValue("returnParameters").findValues("parameters");
        List<ParameterDeclaration> returnParameters =
            parameters.getFirst().isEmpty() ? List.of()
                    : parameters.stream().map(this::parseParam).toList();
        // List<JsonNode> statements =
        // List<ParameterDeclaration> inputParamenters =
        // statements.getFirst().isEmpty() ? List.of() : statements.stream().map(it -> {
        // return parseParam(it.findValue("expression"));
        // }).toList();
        List<ParameterDeclaration> inputParamenters =
            node.findValue("parameters").findValue("parameters").valueStream()
                    .map(this::parseParam).toList();

        Block body = parseBlock(node.findValue("body")); // TODO
        return new FunctionDeclaration(new Name(name), returnParameters, inputParamenters, body);
    }

    private Block parseBlock(JsonNode jsonBody) {
        // List<JsonNode> statements =
        // if (statements.getFirst().isEmpty()) {
        // return new Block(List.of());
        // }
        List<Statement> blockStatements =
            jsonBody.findValue("statements").valueStream().map(this::parseStatement).toList();
        // statements.stream().map(this::parseStatement).toList();
        return new Block(blockStatements);
    }

    private @NonNull Statement parseStatement(JsonNode statement) {
        JsonNode expSt = statement.findValue("expression");
        String nodeType = expSt.findValue("nodeType").asText();
        return switch (nodeType) {
            case "Assignment" ->
                new AssignmentStatement(parseExpression(expSt.findValue("leftHandSide")),
                    parseExpression(expSt.findValue("rightHandSide")));
            case "Identifier" -> new ReturnStatment(parseExpression(expSt));
            default -> throw new RuntimeException("Assignment type " + nodeType + " not supported");
        };

    }

    private ParameterDeclaration parseParam(JsonNode node) {
        final String fieldName = node.findValue("name").asText();
        final String fieldType =
            node.findValue("typeDescriptions").findValue("typeString").asText();

        final ParameterDeclaration field =
            new ParameterDeclaration(new Name(fieldName),
                new TypeReference(new Name(fieldType)));
        final int id = node.findValue("id").asInt();
        id2Name.put(id, field);

        return field;
    }

    private StateVariableDeclaration parseField(JsonNode fieldNode) {
        final String fieldName = fieldNode.findValue("name").asText();
        final String fieldType = fieldNode.findValue("typeName").findValue("name").asText();
        // boolean isPrimitive =
        // fieldNode.findValue("typeName").findValue("nodeType").asText().equals("ElementaryTypeName");

        // TODO: Implement modifiers
        String visibility = fieldNode.findValue("visibility").asText();

        JsonNode initializer = fieldNode.findValue("value");
        Expression initializerExp = null;
        if (initializer != null) {
            initializerExp = parseExpression(initializer);
        }

        final StateVariableDeclaration field =
            new StateVariableDeclaration(new Name(fieldName),
                new TypeReference(new Name(fieldType)),
                initializerExp);
        final int id = fieldNode.findValue("id").asInt();
        id2Name.put(id, field);

        return field;
    }

    private Expression parseExpression(JsonNode initializer) {
        final String nodeType = initializer.findValue("nodeType").asText();
        return switch (nodeType) {
            case "Literal" -> parseLiteral(initializer);
            case "BinaryOperation" -> parseBinaryOperation(initializer);
            case "Identifier" -> parseIdentifier(initializer);
            default -> throw new RuntimeException("Not yet supported expression type: " + nodeType);
        };
    }

    private Expression parseBinaryOperation(JsonNode initializer) {
        // To be Implemented
        Expression leftExpression = null;
        Expression rightExpression = null;

        final String operator = initializer.findValue("operator").asText();
        switch (operator) {
            case "+", "-", "*":
                leftExpression = parseExpression(initializer.findValue("leftExpression"));
                rightExpression = parseExpression(initializer.findValue("rightExpression"));
                return switch (operator) {
                    case "+" -> new AddOperation(leftExpression, rightExpression);
                    case "-" -> new SubtractionOperation(leftExpression, rightExpression);
                    case "*" -> new MultiplicationOperation(leftExpression, rightExpression);
                    default -> throw new IllegalStateException("Impossible case");
                };
            default:
                throw new RuntimeException("Not yet supported binary operation: " + operator);
        }
    }

    private VariableReference parseIdentifier(JsonNode literal) {
        final String name = literal.findValue("name").asText();
        final int referenceDeclarationId = literal.findValue("referencedDeclaration").asInt();
        final String type_str =
            literal.findValue("typeDescriptions").findValue("typeString").asText();
        final Type type = getType(type_str);

        final Declaration declaration = id2Name.get(referenceDeclarationId);
        return switch (declaration) {
            case StateVariableDeclaration stateVarDeclaration ->
                new StateVariableReference(new Name(name), stateVarDeclaration, type);
            case ParameterDeclaration parameterDeclaration ->
                new ParameterVariableReference(new Name(name), parameterDeclaration, type);
            case null -> throw new RuntimeException(
                "Unknown reference declaration " + referenceDeclarationId);
            default -> throw new RuntimeException(
                "Unexpected reference declaration " + declaration + " expected a state variable.");
        };
    }

    private Type getType(String type_str) {
        Type type = switch (type_str) {
            case "uint256" -> UINT256;
            case "bool" -> BOOL;
            default -> throw new IllegalStateException("Type " + type_str + " not covered");
        };
        return type;
    }

    private Literal parseLiteral(JsonNode literal) {
        final String kind = literal.findValue("kind").asText();
        return switch (kind) {
            case "number" -> {
                String initializerExp = literal.findValue("value").asText();
                yield new Uint256Literal(BigIntegerParser.parseWithFastParser(initializerExp));
            }
            case "bool" -> {
                String initializerExp = literal.findValue("value").asText();
                yield initializerExp.equals("true") ? BoolLiteral.TRUE : BoolLiteral.FALSE;
            }
            // FIX!!!!
            default -> throw new RuntimeException("Not yet supported literal");
        };
    }
}
