/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package org.key_project.solidity.logic.parser;

import java.io.IOException;
import java.math.BigInteger;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

import org.key_project.logic.Name;
import org.key_project.solidity.logic.ast.SolidityProgramElement;
import org.key_project.solidity.logic.ast.abstractions.Type;
import org.key_project.solidity.logic.ast.declarations.ContractDeclaration;
import org.key_project.solidity.logic.ast.declarations.Declaration;
import org.key_project.solidity.logic.ast.declarations.FieldDeclaration;
import org.key_project.solidity.logic.ast.expressions.*;
import org.key_project.solidity.logic.ast.expressions.Identifier;
import org.key_project.solidity.logic.ast.references.TypeReference;

import com.fasterxml.jackson.core.io.BigIntegerParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import static org.key_project.solidity.logic.ast.abstractions.PrimitiveType.UINT256;

///
/// Parses the JSON representation of a solidity source unit generated by {@code solc} and converts
/// it
/// into a KeY for Solidity AST representation
///
public class SolJSONParser {

    /// keeps track of JSON ids assigned to declarations, required for resolving field references,
    /// types etc.
    /// TODO: what if a type under declaration references itself (is that possible in Solidity?)
    private HashMap<String, Declaration> id2Name = new HashMap<>();

    /// parses the Solidity file found at the provided [URI] and converts it into a
    /// list of [SolidityProgramElement]s of declarations representing the Solidity programs
    /// @param file the URI where to find the Solidity code
    /// @return list of top level declarations (usually contracts) representing the Solidity code
    public List<SolidityProgramElement> parse(URI file) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(file.toURL());
        return json2SolidityAST(root);
    }

    /// convert the JSON AST representation into a KeY for Solidity representation
    /// @param root the root node representing the JSON AST
    /// @return the KeY AST representation of {@code root}
    private List<SolidityProgramElement> json2SolidityAST(JsonNode root) {
        if ("SourceUnit".equals(root.findValue("nodeType").asText())) {
            return parseSourceUnit(root.findValues("nodes"));
        }
        return new ArrayList<>();
    }

    private List<SolidityProgramElement> parseSourceUnit(List<JsonNode> nodes) {
        List<SolidityProgramElement> elements = new ArrayList<>();
        for (var node : nodes) {
            if (node.findValue("contractKind").asText().equals("contract")) {
                elements.add(parseContract(node));
            }
        }
        return elements;
    }


    private ContractDeclaration parseContract(JsonNode contractNode) {
        String contractName = contractNode.findValue("canonicalName").asText(); // there is also a
        // field "name"
        // now retrieve declared fields, functions, structs etc.
        List<FieldDeclaration> fields = new ArrayList<>();

        for (Iterator<JsonNode> it = contractNode.findValue("nodes").elements(); it.hasNext();) {
            final JsonNode node = it.next();
            final String nodeType = node.findValue("nodeType").asText();
            switch (nodeType) {
                case "VariableDeclaration" -> fields.add(parseField(node));
                default -> throw new RuntimeException("Unknown node type " + nodeType);
            }
        }

        final ContractDeclaration cdecl = new ContractDeclaration(new Name(contractName), fields);
        String contractId = contractNode.findValue("id").asText();
        id2Name.put(contractId, cdecl);
        return cdecl;
    }

    private FieldDeclaration parseField(JsonNode fieldNode) {
        final String fieldName = fieldNode.findValue("name").asText();
        final String fieldType = fieldNode.findValue("typeName").findValue("name").asText();
        // boolean isPrimitive =
        // fieldNode.findValue("typeName").findValue("nodeType").asText().equals("ElementaryTypeName");

        // TODO: Implement modifiers
        String visibility = fieldNode.findValue("visibility").asText();

        JsonNode initializer = fieldNode.findValue("value");
        Expression initializerExp = null;
        if (initializer != null) {
            initializerExp = parseExpression(initializer);
        }

        final FieldDeclaration field =
            new FieldDeclaration(new Name(fieldName), new TypeReference(new Name(fieldType)),
                initializerExp);
        final String id = fieldNode.findValue("id").asText();
        id2Name.put(id, field);

        return field;
    }

    private Expression parseExpression(JsonNode initializer) {
        final String nodeType = initializer.findValue("nodeType").asText();
        return switch (nodeType) {
            case "Literal" -> parseLiteral(initializer);
            case "BinaryOperation" -> parseBinaryOperation(initializer);
            case "Identifier" -> parseIdentifier(initializer);
            default -> throw new RuntimeException("Not yet supported expression type: " + nodeType);
        };
    }

    private Expression parseBinaryOperation(JsonNode initializer) {
        // To be Implemented
        JsonNode leftExpression = null;
        JsonNode rightExpression = null;

        final String operator = initializer.findValue("operator").asText();
        switch (operator) {
            case "+":
                leftExpression = initializer.findValue("leftExpression");
                rightExpression = initializer.findValue("rightExpression");
                return new AddOperation(parseExpression(leftExpression),
                    parseExpression(rightExpression));
            default:
                throw new RuntimeException("Not yet supported binary operation: " + operator);
        }
    }

    private Identifier parseIdentifier(JsonNode literal) {
        final String name = literal.findValue("name").asText();
        final int id = literal.findValue("referencedDeclaration").asInt();
        String type_str = literal.findValue("typeDescriptions").findValue("typeString").asText();
        Type type = switch (type_str) {
            case "uint256" -> UINT256;
            default -> throw new IllegalStateException("Type " + type_str + " not covered");
        };
        return new Identifier(name, id, type);
    }

    private Literal parseLiteral(JsonNode literal) {
        final String kind = literal.findValue("kind").asText();
        return switch (kind) {
            case "number" -> {
                String initializerExp = literal.findValue("value").asText();
                yield new Uint256Literal(BigIntegerParser.parseWithFastParser(initializerExp));
            }
            case "bool" -> new Uint256Literal(BigInteger.ZERO); // FIX!!!!
            default -> throw new RuntimeException("Not yet supported literal");
        };
    }
}
