/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package org.key_project.solidity.program.parser;

import java.io.IOException;
import java.math.BigInteger;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.HashSet;
import java.util.stream.Stream;

import org.key_project.logic.Name;
import org.key_project.logic.SyntaxElement;
import org.key_project.logic.sort.Sort;
import org.key_project.solidity.common.Services;
import org.key_project.solidity.logic.op.ProgramVariable;
import org.key_project.solidity.logic.sort.SortImpl;
import org.key_project.solidity.program.ast.Resolver;
import org.key_project.solidity.program.ast.SolidityInfo;
import org.key_project.solidity.program.ast.abstractions.*;
import org.key_project.solidity.program.ast.declarations.*;
import org.key_project.solidity.program.ast.declarations.FunctionEnums.*;
import org.key_project.solidity.program.ast.expressions.*;
import org.key_project.solidity.program.ast.expressions.literals.*;
import org.key_project.solidity.program.ast.expressions.operators.*;
import org.key_project.solidity.program.ast.references.*;
import org.key_project.solidity.program.ast.statement.*;
import org.key_project.util.collection.ImmutableArray;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.*;

import static org.key_project.solidity.program.ast.abstractions.PrimitiveType.*;
import static org.key_project.solidity.program.ast.expressions.literals.BoolLiteral.*;

///
/// Parses the JSON representation of a solidity source unit generated by {@code solc} and converts
/// it
/// into a KeY for Solidity AST representation
///
public class SolJSONParser {

    /// keeps track of JSON ids assigned to declarations, required for resolving field references,
    /// types etc.
    /// TODO: what if a type under declaration references itself (is that possible in Solidity?)
    private final HashMap<Integer, SyntaxElement> id2Name = new HashMap<>();

    private final HashMap<Integer, TupleType> functionId2Type = new HashMap<>();
    private final Set<Integer> contractIds = new HashSet<>();


    private final Services services;

    public SolJSONParser() {
        services = new Services();
    }

    public SolJSONParser(Services services) {
        this.services = services;
    }

    /// parses the Solidity file found at the provided [URI] and converts it into a
    /// list of [SyntaxElement]s of declarations representing the Solidity programs
    /// @param file the URI where to find the Solidity code
    /// @return list of top level declarations (usually contracts) representing the Solidity code
    public List<SyntaxElement> parse(URI file) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(file.toURL());
        return json2SolidityAST(root);
    }

    public List<SyntaxElement> parse(String contract) throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        JsonNode root = mapper.readTree(contract);
        return json2SolidityAST(root);
    }

    /// convert the JSON AST representation into a KeY for Solidity representation
    /// @param root the root node representing the JSON AST
    /// @return the KeY AST representation of {@code root}
    private List<SyntaxElement> json2SolidityAST(JsonNode root) {
        if ("SourceUnit".equals(root.get("nodeType").asText())) {
            return parseSourceUnit(root.get("nodes").valueStream().toList());
        }
        return new ArrayList<>();
    }

    private List<SyntaxElement> parseSourceUnit(List<JsonNode> nodes) {
        List<SyntaxElement> elements = new ArrayList<>();
        for (var node : nodes) {
            if (node.get("contractKind").asText().equals("contract")) {
                elements.add(parseContract(node));
            }
        }
        return elements;
    }


    private ContractDeclaration parseContract(JsonNode contractNode) {
        String contractName = contractNode.get("canonicalName").asText(); // there is also a
        final int contractId = contractNode.get("id").asInt();
        contractIds.add(contractId);
        List<StateVariableDeclaration> fields = new ArrayList<>();
        List<FunctionDeclaration> functions = new ArrayList<>();
        List<StructDeclaration> structs = new ArrayList<>();
        List<ModifierDeclaration> modifiers = new ArrayList<>();
        List<EnumDeclaration> enums = new ArrayList<>();

        SolidityInfo info = services.getSolidityInfo();
        KeYSolidityType contractType = info.getKeYSolidityType(contractName);

        if (contractType == null) {
            Sort contractSort = services.getNamespaces().sorts().lookup(contractName);
            if (contractSort == null) {
                contractSort = new SortImpl(new Name(contractName), false); // HACK: inheritance
                services.getNamespaces().sorts().addSafely(contractSort);
            }
            contractType = new KeYSolidityType(contractSort);
        }

        assert contractType.getSolidityType() == null : "Contract has already been parsed";

        for (Iterator<JsonNode> it = contractNode.get("nodes").elements(); it.hasNext();) {
            final JsonNode node = it.next();
            final String nodeType = node.get("nodeType").asText();
            switch (nodeType) {
                case "VariableDeclaration" -> fields.add(parseVariableField(node));
                case "FunctionDefinition" -> functions.add(parseFunction(node));
                case "StructDefinition" -> structs.add(parseStruct(node, contractId));
                case "ModifierDefinition" -> modifiers.add(parseModifier(node));
                case "EnumDefinition" -> enums.add(parseEnum(node));
                default -> throw new RuntimeException("Unknown node type " + nodeType);
            }
        }

        final ContractDeclaration cDecl =
            new ContractDeclaration(new Name(contractName), fields, structs, modifiers,
                functions, enums);

        contractType.setSolidityType(cDecl);

        id2Name.put(contractId, cDecl);
        completeReferences(cDecl);
        return cDecl;
    }

    private void completeReferences(SyntaxElement cDecl) {
        List<SyntaxElement> elements = new ArrayList<>();
        queueRefs(cDecl, elements);
        for (SyntaxElement el : elements) {
            if (el instanceof Resolver)
                ((Resolver) el).resolve(id2Name);
            if(el instanceof ProgramVariable){
                ((ProgramVariable) el).getKeySolidityType().resolve(id2Name);
            }
        }
    }

    private void queueRefs(SyntaxElement cDecl, List<SyntaxElement> queue) {
        for (int i = 0; i < cDecl.getChildCount(); i++) {
            SyntaxElement child = cDecl.getChild(i);
            queue.add(child);
            queueRefs(child, queue);
        }
    }


    private EnumDeclaration parseEnum(JsonNode node) {
        final int id = node.get("id").asInt();
        String name = node.get("name").asText();
        List<MemberEnumDeclaration> members =
            node.get("members").valueStream().map(this::parseMemberEnum).toList();
        EnumDeclaration enumDeclaration = new EnumDeclaration(new Name(name), members);
        addTypeToServices(enumDeclaration);
        id2Name.put(id, enumDeclaration);
        return enumDeclaration;
    }

    private MemberEnumDeclaration parseMemberEnum(JsonNode node) {
        String name = node.get("name").asText();
        int id = node.get("id").asInt();
        MemberEnumDeclaration member = new MemberEnumDeclaration(new Name(name));
        id2Name.put(id, member);
        return member;
    }

    private ModifierDeclaration parseModifier(JsonNode node) {
        final String name = node.get("name").asText();
        List<ProgramVariable> inputParameters =
            node.get("parameters").get("parameters").valueStream()
                    .map(this::parseParam).toList();
        Block body = parseBlock(node.get("body"));
        Visibility visibility = Visibility.fromString(node.get("visibility").asText());
        ModifierDeclaration modifier =
            new ModifierDeclaration(new Name(name), inputParameters, body, visibility);
        id2Name.put(node.get("id").asInt(), modifier);
        return modifier;
    }

    private StructDeclaration parseStruct(JsonNode structNode, int contractId) {
        String name = structNode.get("name").asText();
        List<FieldDeclaration> fields =
            structNode.get("members").valueStream().map(this::parseField).toList();

        StructDeclaration stDecl = new StructDeclaration(new Name(name), fields, contractId);
        addTypeToServices(stDecl);
        id2Name.put(structNode.get("id").asInt(), stDecl);

        return stDecl;
    }

    private FieldDeclaration parseField(JsonNode fieldNode) {
        final String fieldName = fieldNode.get("name").asText();
        final String fieldType = fieldNode.get("typeName").get("name").asText();

        FieldDeclaration field =
            new FieldDeclaration(new Name(fieldName), new TypeReference(new Name(fieldType)));
        id2Name.put(fieldNode.get("id").asInt(), field);
        return field;
    }

    private FunctionDeclaration parseFunction(JsonNode node) {
        final int id = node.get("id").asInt();
        final String name = node.get("name").asText();
        Stream<JsonNode> parameters =
            node.get("returnParameters").get("parameters").valueStream();
        List<ProgramVariable> returnParameters = parameters.map(this::parseParam).toList();
        TupleType returnType = getTupleType(returnParameters.stream().map(ProgramVariable::getType).toList());
        functionId2Type.put(id, returnType);
        List<ProgramVariable> inputParamenters =
            node.get("parameters").get("parameters").valueStream()
                    .map(this::parseParam).toList();

        Block body = parseBlock(node.get("body"));
        String kind = node.get("kind").asText();
        Visibility visibility = Visibility.fromString(node.get("visibility").asText());
        StateMutability stateMutability =
            StateMutability.valueOf(node.get("stateMutability").asText());
        List<ModifierReference> modifiers =
            node.get("modifiers").valueStream().map(this::parseModifierRefence).toList();
        JsonNode documentationNode = node.get("documentation");
        String documentation = "";
        if (documentationNode != null)
            documentation = documentationNode.get("text").asText();
        FunctionDeclaration function = new FunctionDeclaration(new Name(name), returnParameters, returnType,
            inputParamenters, body, kind, visibility, stateMutability, modifiers, documentation);
        id2Name.put(id, function);
        return function;
    }

    private ModifierReference parseModifierRefence(JsonNode node) {
        String name = node.get("modifierName").get("name").asText();
        return new ModifierReference(name);
    }

    private Block parseBlock(JsonNode jsonBody) {
        List<Statement> blockStatements =
            jsonBody.get("statements").valueStream().map(this::parseStatement).toList();
        return new Block(blockStatements);
    }

    private CatchClause parseCatchClause(JsonNode jsonBody) {
        Block block = parseBlock(jsonBody.get("block"));
        if (jsonBody.has("errorName")) {
            String errorName = jsonBody.get("errorName").asText();
            if (!errorName.isEmpty()) {
                List<StatementVariableDeclaration> arguments =
                    jsonBody.get("parameters").get("parameters").valueStream()
                            .map(this::parseDeclaration)
                            .map(StatementVariableDeclaration.class::cast).toList();
                return new CatchClause(new ImmutableArray<>(arguments), block);
            }
        }
        return new CatchClause(block);
    }

    private @NonNull Statement parseStatement(JsonNode statement) {
        String type = statement.get("nodeType").asText();
        if (statement.has("expression")) {
            Expression expression = parseExpression(statement.get("expression"));
            return switch (type) {
                case "ExpressionStatement" -> new ExpressionStatement(expression);
                case "Return" -> new ReturnStatement(expression);
                default ->
                    throw new RuntimeException("Statement type " + type + " is not supported");
            };
        } else if (statement.has("declarations")) {
            List<Declaration> declarations = statement.get("declarations").valueStream()
                    .map(this::parseDeclaration).toList();
            Expression initialValue = findOrNullExpression(statement, "initialValue");
            return new DeclarationStatement(declarations, initialValue);
        } else if (statement.has("condition")) {
            Expression condition = parseExpression(statement.get("condition"));
            if (type.equals("IfStatement")) {
                Statement trueBody = parseStatement(statement.get("trueBody"));
                if (!statement.has("falseBody"))
                    return new ConditionStatement(condition, trueBody);
                Statement falseBody = parseStatement(statement.get("falseBody"));
                return new ConditionStatement(condition, trueBody, falseBody);

            } else if (type.equals("WhileStatement")) {
                Statement body = parseStatement(statement.get("body"));
                return new WhileStatement(condition, body);

            }
        } else if (statement.has("statements")) {
            return parseBlock(statement);
        }

        return switch (type) {
            case "Continue" -> new ContinueStatement();
            case "Break" -> new BreakStatement();
            case "ForStatement" -> {
                ForInit init = statement.has("initializationExpression")
                        ? new ForInit(
                            parseExpression(statement.get("initializationExpression")))
                        : null;
                Expression condition = findOrNullExpression(statement, "condition");
                ForUpdate forUpdate = statement.has("loopExpression")
                        ? new ForUpdate(parseExpression(statement.get("loopExpression")))
                        : null;
                Statement body = parseStatement(statement.get("body"));
                yield new ForStatement(init, condition, forUpdate, body);
            }
            case "DoWhileStatement" -> {
                Expression condition = parseExpression(statement.get("condition"));
                Statement body = parseStatement(statement.get("body"));
                yield new DoWhileStatement(condition, body);
            }
            case "TryStatement" -> {
                Expression expression =
                    parseExpression(statement.get("externalCall").get("expression"));
                List<JsonNode> clausesList = statement.get("clauses").valueStream().toList();
                JsonNode firstClause = clausesList.getFirst();
                List<ProgramVariable> returns =
                        firstClause.get("parameters") == null ? List.of()
                                : firstClause.get("parameters").get("parameters")
                                .valueStream().map(this::parseParam).toList();
                Block body = parseBlock(firstClause.get("block"));
                List<CatchClause> clauses = clausesList.stream().skip(1)
                        .map(this::parseCatchClause)
                        .toList();
                yield new TryStatement(expression, new ImmutableArray<>(returns), body,
                    new ImmutableArray<>(clauses));
            }
            case "PlaceholderStatement" -> new PlaceholdStatement();
            default -> throw new IllegalStateException("Statement does not have type " + type);
        };
    }

    private Declaration parseDeclaration(JsonNode declaration) {
        final int id = declaration.get("id").asInt();
        String nameS = declaration.get("name").asText();
        Name name = new Name(nameS);
        JsonNode typeNameNode = declaration.get("typeName");
        Type type = parseType(typeNameNode);
        KeYSolidityType ksType = getUndeclaredSolidityType(type);
        DataLocation dataLocation =
                DataLocation.fromString(declaration.get("storageLocation").asText());
        ProgramVariable programVariable = new ProgramVariable(name, ksType.getSort(), ksType, dataLocation);
        Declaration decl = new StatementVariableDeclaration(programVariable);
        id2Name.put(id, decl);
        return decl;

    }

    private @NonNull DynamicArrayType getDynamicArrayType(Type primitiveType) {
        return (DynamicArrayType) services.getSolidityInfo().getDynamicTypeMap(primitiveType.name());
    }

    private @NonNull ArrayType getStaticArrayType(Type primitiveType, int size) {
        return (ArrayType) services.getSolidityInfo().getStaticTypeMap(primitiveType.name(), size);
    }

    private ProgramVariable parseParam(JsonNode node) {
        final int id = node.get("id").asInt();
        final String fieldName = node.get("name").asText();
        final String dataLocationS = node.get("storageLocation").asText();
        final DataLocation dataLocation = DataLocation.fromString(dataLocationS);

        ProgramVariable programVariable;
        if (node.get("typeName").has("referencedDeclaration")) {
            int typeId = node.get("typeName").get("referencedDeclaration").asInt();
            Type typeRef = (Type) id2Name.get(typeId);

            final KeYSolidityType kst = getUndeclaredSolidityType(typeRef);
            programVariable = new ProgramVariable(new Name(fieldName),
                kst.getSort(), kst, dataLocation);
        } else {
            Type type = parseTypeName(node);
            final KeYSolidityType kst = getUndeclaredSolidityType(type);
            programVariable = new ProgramVariable(new Name(fieldName),
                kst.getSort(), kst, dataLocation);
        }
        id2Name.put(id, programVariable);

        return programVariable;
    }

    private Type parseType(JsonNode node) {
        String typeName = node.get("nodeType").asText();
        return switch (typeName) {
            case "ElementaryTypeName" -> getPrimitiveType(node.get("name").asText());
            case "ArrayTypeName" -> {
                Type baseType = parseType(node.get("baseType"));
                if (node.has("length")) {
                    int size = node.get("length").get("value").asInt();
                    yield getStaticArrayType(baseType, size);
                } else
                    yield getDynamicArrayType(baseType);
            }
            case "Mapping" -> getMappingType(parseType(node.get("keyType")), parseType(node.get("valueType")));
            case "UserDefinedTypeName" -> (Type) id2Name.get(node.get("referencedDeclaration").asInt());
            case "Identifier" -> SolidityInfo.getPrimitiveType(node.get("typeDescriptions").get("typeString").asText());
            default -> throw new RuntimeException("Type " + typeName + " not covered");
        };
    }

    private @NonNull MappingType getMappingType(Type keyType, Type valueType) {
        return services.getSolidityInfo().getMappingTypeMap(keyType, valueType);
    }

    private StateVariableDeclaration parseVariableField(JsonNode fieldNode) {
        final int id = fieldNode.get("id").asInt();
        final String fieldName = fieldNode.get("name").asText();
        JsonNode typeName = fieldNode.get("typeName");
        Type expType = null;
        int idRef = -1;
        if (typeName.has("referencedDeclaration")) {
            idRef = typeName.get("referencedDeclaration").asInt();
            if (id2Name.containsKey(idRef)) {
                expType = (Type) id2Name.get(idRef);
            }
        } else
            expType = parseTypeName(fieldNode);

        Visibility visibility = Visibility.fromString(fieldNode.get("visibility").asText());

        Expression initializerExp = null;
        if (fieldNode.has("value")) {
            initializerExp = parseExpression(fieldNode.get("value"));
        }

        KeYSolidityType type = expType == null ? new KeYSolidityType(idRef) : getUndeclaredSolidityType(expType);
        ProgramVariable programVariable = new ProgramVariable(new Name(fieldName),
                type, DataLocation.Storage);
        StateVariableDeclaration field = new StateVariableDeclaration(programVariable, initializerExp, visibility);
        id2Name.put(id, field);

         return field;
    }

    Type parseReferenceTypeDeclaration(JsonNode expNode) {
        int id = expNode.get("referencedDeclaration").asInt();
        SyntaxElement decl = id2Name.get(id);
        return Optional.ofNullable(decl).map(v -> switch (v){
            case Type tp -> tp;
            case FunctionDeclaration fd -> fd.getType();
            case StatementVariableDeclaration svd -> svd.getProgramVariable().getType();
            default -> null;
        }).orElseGet(() -> {
            if (functionId2Type.containsKey(id))
                return functionId2Type.get(id);
            else if (contractIds.contains(id))
                return ADDRESS;
            return parseType(expNode);
        });
    }

    private Expression parseExpression(JsonNode initializer) {
        final String nodeType = initializer.get("nodeType").asText();
        return switch (nodeType) {
            case "Literal" -> parseLiteral(initializer);
            case "BinaryOperation" -> parseBinaryOperation(initializer);
            case "UnaryOperation" -> parseUnaryOperation(initializer);
            case "Identifier" -> parseIdentifier(initializer);
            case "Assignment" -> parseAssignment(initializer);
            case "MemberAccess" -> parseMemberAccess(initializer);
            case "IndexAccess" -> parseIndexAccess(initializer);
            case "Conditional" -> parseConditional(initializer);
            case "TupleExpression" -> parseTuple(initializer);
            case "IndexRangeAccess" -> parseIndexRangeAccess(initializer);
            case "FunctionCall" -> parseFunctionCall(initializer);
            case "ElementaryTypeNameExpression" -> parseElementaryExpression(initializer);
            case "ExpressionStatement" -> parseExpression(initializer.get("expression"));
            case "NewExpression" -> parseNewExpression(initializer);
            default -> throw new RuntimeException("Not yet supported expression type: " + nodeType);
        };
    }

    private Expression parseNewExpression(JsonNode initializer) {
        String functionDef =
            initializer.get("typeDescriptions").get("typeString").asText();
        Type type = parseTypeName(initializer);
        return new NewExpression(functionDef, type);
    }

    private Expression parseElementaryExpression(JsonNode initializer) {
        Type type = parseTypeName(initializer);
        return new ElementaryExpression(type);
    }

    private Type parseTypeName(JsonNode initializer) {
        return parseType(initializer.get("typeName"));
    }

    private Expression parseFunctionCall(JsonNode initializer) {
        JsonNode expNode = initializer.get("expression");
        Type expType = expNode.has("referencedDeclaration") ?
                parseReferenceTypeDeclaration(expNode) :
                parseTypeName(expNode);
        Expression functionExp = parseExpression(expNode);
        List<Expression> arguments =
            initializer.get("arguments").valueStream().map(this::parseExpression).toList();
        return new FunctionCallExpression(expType, functionExp, arguments);
    }

    private Expression parseIndexRangeAccess(JsonNode initializer) {
        Expression baseExp = parseExpression(initializer.get("baseExpression"));
        Expression startExp = parseExpression(initializer.get("startExpression"));
        Expression endExp = parseExpression(initializer.get("endExpression"));
        return new IndexRangeExpression(baseExp, startExp, endExp, baseExp.getType());
    }

    private Expression parseTuple(JsonNode initializer) {
        List<Expression> components =
            initializer.get("components").valueStream().map(this::parseExpression).toList();
        List<Type> types = components.stream().map(Expression::getType).toList();
        return new TupleExpression(getTupleType(types), components);
    }

    private Expression parseConditional(JsonNode initializer) {
        Expression cond = parseExpression(initializer.get("condition"));
        Expression falseExpression = parseExpression(initializer.get("falseExpression"));
        Expression trueExpression = parseExpression(initializer.get("trueExpression"));

        return new TernaryOperator(BOOL, cond, falseExpression, trueExpression);
    }

    private Expression parseIndexAccess(JsonNode initializer) {
        int idLeftRef =
            initializer.get("baseExpression").get("referencedDeclaration").asInt();
        Expression indexExp = parseExpression(initializer.get("indexExpression"));
        ProgramVariable leftExp = getProgramVariable(idLeftRef);
        return new IndexExpression(leftExp, indexExp);
    }

    private ProgramVariable getProgramVariable(int idLeftRef) {
        Declaration declaration = (Declaration) id2Name.get(idLeftRef);

        return switch (declaration) {
            case StateVariableDeclaration stateVarDeclaration ->
                stateVarDeclaration.getProgramVariable();
            case StatementVariableDeclaration stmVarDeclaration ->
                stmVarDeclaration.getProgramVariable();
            default -> throw new RuntimeException(
                "Declaration " + declaration + " does not have program variable");
        };
    }

    private Expression parseMemberAccess(JsonNode initializer) {
        Expression leftExp = parseExpression(initializer.get("expression"));
        int rightId = initializer.get("referencedDeclaration").asInt();
        JsonNode expNode = initializer.get("expression");
        Type type = expNode.has("referencedDeclaration") ?
                parseReferenceTypeDeclaration(expNode) :
                ADDRESS;
        if (id2Name.containsKey(rightId))
            return new MemberExp(leftExp, id2Name.get(rightId), type);
        return new MemberExp(leftExp, rightId, type);
    }

    private Expression parseAssignment(JsonNode assign) {
        final String op = assign.get("operator").asText();
        Expression left = parseExpression(assign.get("leftHandSide"));
        Expression right = parseExpression(assign.get("rightHandSide"));
        return ParserUtils.parseAssignment(left, right, op);
    }

    private Expression parseUnaryOperation(JsonNode initializer) {
        Expression uExp = parseExpression(initializer.get("subExpression"));
        final String operator = initializer.get("operator").asText();
        boolean prefix = initializer.get("prefix").asBoolean();
        return ParserUtils.parseUnaryOperation(uExp, operator, prefix);
    }

    private Expression parseBinaryOperation(JsonNode initializer) {
        Expression leftExpression = parseExpression(initializer.get("leftExpression"));
        Expression rightExpression = parseExpression(initializer.get("rightExpression"));

        final String operator = initializer.get("operator").asText();
        Type type = getTypeFromDescription(initializer);
        return ParserUtils.parseBinaryOperation(leftExpression, rightExpression, operator, type);
    }

    private Type getTypeFromDescription(JsonNode initializer) {
        String typeIdentifier = initializer.get("typeDescriptions").get("typeIdentifier").textValue();
        return SolidityInfo.getPrimitiveType(typeIdentifier.split("\\$")[0].substring(2).split("_")[0]);
    }

    private Expression parseIdentifier(JsonNode literal) {
        final int idDecl = literal.get("referencedDeclaration").asInt();
        final SyntaxElement declaration = id2Name.get(idDecl);
        Type type = parseReferenceTypeDeclaration(literal);
        return switch (declaration) {
            case StateVariableDeclaration stateVarDeclaration ->
                stateVarDeclaration.getProgramVariable();
            case FunctionDeclaration ignored ->
                new FunctionReference(idDecl, type);
            case StatementVariableDeclaration stmVarDeclaration ->
                stmVarDeclaration.getProgramVariable();
            case EnumDeclaration enumDeclaration ->
                new EnumReference(enumDeclaration, type);
            case ProgramVariable p -> p;
            case null ->
                switch (type) {
                    case TupleType tupleType -> new FunctionReference(idDecl, tupleType);
                    case PrimitiveType tp -> new ContractReference(idDecl, tp);
                    default -> throw new RuntimeException("Type " + type + " is not function or contract");
                };
            default -> throw new RuntimeException(
                "Unexpected reference declaration " + declaration + " expected a state variable.");
        };
    }

    private Literal parseLiteral(JsonNode literal) {
        final String kind = literal.get("kind").asText();
        return switch (kind) {
            case "number" -> {
                String initializerExp = literal.get("value").asText();
                yield new Uint256Literal(new BigInteger(initializerExp));
            }
            case "bool" -> {
                String initializerExp = literal.get("value").asText();
                yield initializerExp.equals("true") ? TRUE : FALSE;
            }
            // FIX!!!!
            default -> throw new RuntimeException("Not yet supported literal");
        };
    }

    private TupleType getTupleType(List<Type> types) {
        return services.getSolidityInfo().getTupleTypeMap(types);
    }

    private @Nullable Expression findOrNullExpression(JsonNode statement, String field) {
        return statement.has(field) ? parseExpression(statement.get(field)) : null;
    }

    private void addTypeToServices(Type type) {
        final Sort sort = type.getSort(services);
        KeYSolidityType ksType = new KeYSolidityType(type, sort);
        services.getSolidityInfo().addType(sort, type);
        services.getNamespaces().sorts().add(sort);
    }

    private @NonNull KeYSolidityType getUndeclaredSolidityType(@NonNull Type type) {
        final Sort sort = type.getSort(services);
        KeYSolidityType ksType = new KeYSolidityType(type, sort);
        services.getSolidityInfo().addType(sort, ksType);
        services.getNamespaces().sorts().add(sort);
        return ksType;
    }
}
