/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package org.key_project.solidity.program.parser;

import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Stream;

import org.key_project.logic.Name;
import org.key_project.solidity.program.ast.SolidityProgramElement;
import org.key_project.solidity.program.ast.abstractions.Type;
import org.key_project.solidity.program.ast.declarations.*;
import org.key_project.solidity.program.ast.expressions.Expression;
import org.key_project.solidity.program.ast.expressions.IndexExpression;
import org.key_project.solidity.program.ast.expressions.MemberExp;
import org.key_project.solidity.program.ast.expressions.literals.BoolLiteral;
import org.key_project.solidity.program.ast.expressions.literals.Literal;
import org.key_project.solidity.program.ast.expressions.literals.Uint256Literal;
import org.key_project.solidity.program.ast.expressions.operators.*;
import org.key_project.solidity.program.ast.expressions.operators.AssignmentExpression;
import org.key_project.solidity.program.ast.references.ParameterVariableReference;
import org.key_project.solidity.program.ast.references.StateVariableReference;
import org.key_project.solidity.program.ast.references.TypeReference;
import org.key_project.solidity.program.ast.references.VariableReference;
import org.key_project.solidity.program.ast.statement.*;

import com.fasterxml.jackson.core.io.BigIntegerParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.NonNull;

import static org.key_project.solidity.program.ast.abstractions.PrimitiveType.*;

///
/// Parses the JSON representation of a solidity source unit generated by {@code solc} and converts
/// it
/// into a KeY for Solidity AST representation
///
public class SolJSONParser {

    /// keeps track of JSON ids assigned to declarations, required for resolving field references,
    /// types etc.
    /// TODO: what if a type under declaration references itself (is that possible in Solidity?)
    private final HashMap<Integer, Declaration> id2Name = new HashMap<>();

    /// parses the Solidity file found at the provided [URI] and converts it into a
    /// list of [SolidityProgramElement]s of declarations representing the Solidity programs
    /// @param file the URI where to find the Solidity code
    /// @return list of top level declarations (usually contracts) representing the Solidity code
    public List<SolidityProgramElement> parse(URI file) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(file.toURL());
        return json2SolidityAST(root);
    }

    public List<SolidityProgramElement> parse(String contract) throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        JsonNode root = mapper.readTree(contract);
        return json2SolidityAST(root);
    }

    /// convert the JSON AST representation into a KeY for Solidity representation
    /// @param root the root node representing the JSON AST
    /// @return the KeY AST representation of {@code root}
    private List<SolidityProgramElement> json2SolidityAST(JsonNode root) {
        if ("SourceUnit".equals(root.findValue("nodeType").asText())) {
            return parseSourceUnit(root.findValues("nodes"));
        }
        return new ArrayList<>();
    }

    private List<SolidityProgramElement> parseSourceUnit(List<JsonNode> nodes) {
        List<SolidityProgramElement> elements = new ArrayList<>();
        for (var node : nodes) {
            if (node.findValue("contractKind").asText().equals("contract")) {
                elements.add(parseContract(node));
            }
        }
        return elements;
    }


    private ContractDeclaration parseContract(JsonNode contractNode) {
        String contractName = contractNode.findValue("canonicalName").asText(); // there is also a
        // field "name"
        // now retrieve declared fields, functions, structs etc.
        List<StateVariableDeclaration> fields = new ArrayList<>();
        List<FunctionDeclaration> functions = new ArrayList<>();
        List<StructDeclaration> structs = new ArrayList<>();

        for (Iterator<JsonNode> it = contractNode.findValue("nodes").elements(); it.hasNext();) {
            final JsonNode node = it.next();
            final String nodeType = node.findValue("nodeType").asText();
            switch (nodeType) {
                case "VariableDeclaration" -> fields.add(parseVariableField(node));
                case "FunctionDefinition" -> functions.add(parseFunction(node));
                case "StructDefinition" -> structs.add(parseStruct(node));
                default -> throw new RuntimeException("Unknown node type " + nodeType);
            }
        }

        final ContractDeclaration cdecl =
            new ContractDeclaration(new Name(contractName), fields, structs, functions);
        final int contractId = contractNode.findValue("id").asInt();
        id2Name.put(contractId, cdecl);
        return cdecl;
    }

    private StructDeclaration parseStruct(JsonNode structNode) {
        String name = structNode.findValue("name").asText();
        List<FieldDeclaration> fields = structNode.findValue("members").valueStream().map(this::parseField).toList();

        return new StructDeclaration(new Name(name), fields);
    }

    private FieldDeclaration parseField(JsonNode fieldNode) {
        final String fieldName = fieldNode.findValue("name").asText();
        final String fieldType = fieldNode.findValue("typeName").findValue("name").asText();

        return new FieldDeclaration(new Name(fieldName), new TypeReference(new Name(fieldType)));
    }

    private FunctionDeclaration parseFunction(JsonNode node) {
        final String name = node.findValue("name").asText();
        Stream<JsonNode> parameters = node.findValue("returnParameters").findValue("parameters").valueStream();
        List<ParameterDeclaration> returnParameters = parameters.map(this::parseParam).toList();
        List<ParameterDeclaration> inputParamenters =
            node.findValue("parameters").findValue("parameters").valueStream()
                    .map(this::parseParam).toList();

        Block body = parseBlock(node.findValue("body")); // TODO
        return new FunctionDeclaration(new Name(name), returnParameters, inputParamenters, body);
    }

    private Block parseBlock(JsonNode jsonBody) {
        // List<JsonNode> statements =
        // if (statements.getFirst().isEmpty()) {
        // return new Block(List.of());
        // }
        List<Statement> blockStatements =
            jsonBody.findValue("statements").valueStream().map(this::parseStatement).toList();
        // statements.stream().map(this::parseStatement).toList();
        return new Block(blockStatements);
    }

    private @NonNull Statement parseStatement(JsonNode statement) {
        String type = statement.findValue("nodeType").asText();
        if(statement.has("expression")) {
            Expression expression = parseExpression(statement.findValue("expression"));
            return switch (type) {
                case "ExpressionStatement" -> new ExpressionStatement(expression);
                case "Return" -> new ReturnStatment(expression);
                default -> throw new RuntimeException("Statement type " + type + " is not supported");
            };
        }
        else if(statement.has("declarations")) {
            List<MemoryDeclaration> declarations = statement.findValue("declarations").valueStream().map(this::parseDeclaration).toList();
            return new DeclarationStatement(declarations);
        }
        else if(statement.has("condition")){
            Expression condition = parseExpression(statement.findValue("condition"));
            if(type.equals("IfStatement")){
                Statement trueBody = parseStatement(statement.findValue("trueBody"));
                if(!statement.has("falseBody"))
                    return new ConditionStatement(condition, trueBody);
                Statement falseBody = parseStatement(statement.findValue("falseBody"));
                return new ConditionStatement(condition, trueBody, falseBody);

            }
            else if(type.equals("WhileStatement")) {
                Statement body = parseStatement(statement.findValue("body"));
                return new WhileStatement(condition, body);

            }
        }
        else if(statement.has("statements")){
            return parseBlock(statement);
        }
        else if(type.equals("Continue")){
            return new ContinueStatement();
        }
        else if(type.equals("Break")){
            return new BreakStatement();
        }


        return null;
    }

    private MemoryDeclaration parseDeclaration(JsonNode declaration){
        String name = declaration.findValue("name").asText();
        String struct = declaration.findValue("typeName").findValue("pathNode").findValue("name").asText();
        return new MemoryDeclaration(new Name(name), struct);
    }

    private ParameterDeclaration parseParam(JsonNode node) {
        final String fieldName = node.findValue("name").asText();
        final String fieldType =
            node.findValue("typeDescriptions").findValue("typeString").asText();

        final ParameterDeclaration field =
            new ParameterDeclaration(new Name(fieldName),
                new TypeReference(new Name(fieldType)));
        final int id = node.findValue("id").asInt();
        id2Name.put(id, field);

        return field;
    }

    private StateVariableDeclaration parseVariableField(JsonNode fieldNode) {
        final String fieldName = fieldNode.findValue("name").asText();
        final String fieldType = fieldNode.findValue("typeName").findValue("name").asText();
        // boolean isPrimitive =
        // fieldNode.findValue("typeName").findValue("nodeType").asText().equals("ElementaryTypeName");

        // TODO: Implement modifiers
        String visibility = fieldNode.findValue("visibility").asText();

        JsonNode initializer = fieldNode.findValue("value");
        Expression initializerExp = null;
        if (initializer != null) {
            initializerExp = parseExpression(initializer);
        }

        final StateVariableDeclaration field =
            new StateVariableDeclaration(new Name(fieldName),
                new TypeReference(new Name(fieldType)),
                initializerExp);
        final int id = fieldNode.findValue("id").asInt();
        id2Name.put(id, field);

        return field;
    }

    private Expression parseExpression(JsonNode initializer) {
        final String nodeType = initializer.findValue("nodeType").asText();
        Type expType = getType(initializer.findValue("typeDescriptions").findValue("typeString").textValue());
        Expression exp = switch (nodeType) {
            case "Literal" -> parseLiteral(expType, initializer);
            case "BinaryOperation" -> parseBinaryOperation(expType, initializer);
            case "UnaryOperation" -> parseUnaryOperation(expType, initializer);
            case "Identifier" -> parseIdentifier(expType, initializer);
            case "Assignment" -> parseAssignment(expType, initializer);
            case "MemberAccess" -> parseMemberAccess(expType, initializer);
            case "IndexAccess" -> parseIndexAccess(expType, initializer);
            default -> throw new RuntimeException("Not yet supported expression type: " + nodeType);
        };
        return exp;
    }

    private Expression parseIndexAccess(Type expType, JsonNode initializer) {
        String leftExp = initializer.findValue("baseExpression").findValue("name").asText();
        Expression indexExp = parseExpression(initializer.findValue("indexExpression"));
        return new IndexExpression(leftExp, indexExp, expType);
    }

    private Expression parseMemberAccess(Type expType, JsonNode initializer) {
        Expression leftExp = parseExpression(initializer.findValue("expression"));
        String rightName = initializer.findValue("memberName").asText();
        return new MemberExp(leftExp, rightName, expType);
    }

    private Expression parseAssignment(Type expType, JsonNode assign) {
        final String op = assign.findValue("operator").asText();
        Expression left = parseExpression(assign.findValue("leftHandSide"));
        Expression right = parseExpression(assign.findValue("rightHandSide"));
        
        return switch (op) {
            case "=" -> new AssignmentExpression(left, right, expType);
            case "+=" -> new PlusEqualOperator(left, right, expType);
            case "-=" -> new MinusEqualOperator(left, right, expType);
            default -> throw new RuntimeException("Assignment: " + op + " not supported");
        };
    }

    private Expression parseUnaryOperation(Type expType, JsonNode initializer) {
        Expression uExp = parseExpression(initializer.findValue("subExpression"));
        final String operator = initializer.findValue("operator").asText();
        boolean prefix = initializer.findValue("prefix").asBoolean();
        return switch (operator) {
            case "++" -> new PlusPlusOperator(uExp, expType, prefix);
            case "--" -> new MinusMinusOperator(uExp, expType, prefix);
            case "~" -> new BitwiseNotOperator(uExp, expType);
            case "!" -> new NotOperator(uExp, expType);
            case "-" -> new NegateOperator(uExp, expType);
            case "delete" -> new DeleteOperator(uExp, expType);
            default -> throw new RuntimeException("Not yet supported binary operation: " + operator);
        };
    }

    private Expression parseBinaryOperation(Type expType, JsonNode initializer) {
        Expression leftExpression = parseExpression(initializer.findValue("leftExpression"));
        Expression rightExpression = parseExpression(initializer.findValue("rightExpression"));

        final String operator = initializer.findValue("operator").asText();
        return switch (operator) {
            case "+" -> new AddOperator(leftExpression, rightExpression, expType);
            case "-" -> new SubtractionOperator(leftExpression, rightExpression, expType);
            case "*" -> new MultiplicationOperator(leftExpression, rightExpression, expType);
            case "/" -> new DivOperator(leftExpression, rightExpression, expType);
            case "%" -> new ModOperator(leftExpression, rightExpression, expType);
            case "^" -> new ExponentialOperator(leftExpression, rightExpression, expType);
            case "&&" -> new AndOperator(leftExpression, rightExpression, expType);
            case "&" -> new BitwiseAndOperator(leftExpression, rightExpression, expType);
            case "||" -> new OrOperator(leftExpression, rightExpression, expType);
            case "|" -> new BitwiseOrOperator(leftExpression, rightExpression, expType);
            case "!=" -> new UnequalOperator(leftExpression, rightExpression, expType);
            case "==" -> new EqualOperator(leftExpression, rightExpression, expType);
            case ">=" -> new GreaterEqualOperator(leftExpression, rightExpression, expType);
            case ">" -> new GreaterOperator(leftExpression, rightExpression, expType);
            case "<=" -> new LessEqualOperator(leftExpression, rightExpression, expType);
            case "<" -> new LessOperator(leftExpression, rightExpression, expType);
            case "<<" -> new LeftShiftOperator(leftExpression, rightExpression, expType);
            case ">>" -> new RightShiftOperator(leftExpression, rightExpression, expType);
            case ">>>" -> new LogicalRightShiftOperator(leftExpression, rightExpression, expType);
            default ->
                throw new RuntimeException("Not yet supported binary operation: " + operator);
        };
    }

    private VariableReference parseIdentifier(Type expType, JsonNode literal) {
        final String name = literal.findValue("name").asText();
        final int referenceDeclarationId = literal.findValue("referencedDeclaration").asInt();
        final String type_str =
            literal.findValue("typeDescriptions").findValue("typeString").asText();
        final Type type = getType(type_str);

        final Declaration declaration = id2Name.get(referenceDeclarationId);
        return switch (declaration) {
            case StateVariableDeclaration stateVarDeclaration ->
                new StateVariableReference(new Name(name), stateVarDeclaration, type);
            case ParameterDeclaration parameterDeclaration ->
                new ParameterVariableReference(new Name(name), parameterDeclaration, type);
            case null -> throw new RuntimeException(
                "Unknown reference declaration " + referenceDeclarationId);
            default -> throw new RuntimeException(
                "Unexpected reference declaration " + declaration + " expected a state variable.");
        };
    }

    private Type getType(String type_str) {
        if(type_str.contains(" "))
            type_str = type_str.split(" ")[0];
        if(type_str.contains("_"))
            type_str = type_str.split("_")[0];

        Type type = switch (type_str) {
            case "uint256" -> UINT256;
            case "bool" -> BOOL;
            case "int" -> INT;
            case "int256" -> INT;
            case "struct" -> STRUCT;
            default -> throw new IllegalStateException("Type " + type_str + " not covered");
        };
        return type;
    }

    private Literal parseLiteral(Type expType, JsonNode literal) {
        final String kind = literal.findValue("kind").asText();
        return switch (kind) {
            case "number" -> {
                String initializerExp = literal.findValue("value").asText();
                yield new Uint256Literal(BigIntegerParser.parseWithFastParser(initializerExp));
            }
            case "bool" -> {
                String initializerExp = literal.findValue("value").asText();
                yield initializerExp.equals("true") ? BoolLiteral.TRUE : BoolLiteral.FALSE;
            }
            // FIX!!!!
            default -> throw new RuntimeException("Not yet supported literal");
        };
    }
}
