/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package org.key_project.solidity.program.parser;

import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Stream;

import org.jetbrains.annotations.NotNull;
import org.key_project.logic.Name;
import org.key_project.solidity.program.ast.SolidityProgramElement;
import org.key_project.solidity.program.ast.abstractions.Type;
import org.key_project.solidity.program.ast.declarations.*;
import org.key_project.solidity.program.ast.declarations.FunctionEnums.StateMutability;
import org.key_project.solidity.program.ast.declarations.FunctionEnums.Visibility;
import org.key_project.solidity.program.ast.expressions.*;
import org.key_project.solidity.program.ast.expressions.literals.BoolLiteral;
import org.key_project.solidity.program.ast.expressions.literals.Literal;
import org.key_project.solidity.program.ast.expressions.literals.Uint256Literal;
import org.key_project.solidity.program.ast.expressions.operators.*;
import org.key_project.solidity.program.ast.expressions.operators.AssignmentExpression;
import org.key_project.solidity.program.ast.references.*;
import org.key_project.solidity.program.ast.statement.*;

import com.fasterxml.jackson.core.io.BigIntegerParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.NonNull;

import static org.key_project.solidity.program.ast.abstractions.PrimitiveType.*;

///
/// Parses the JSON representation of a solidity source unit generated by {@code solc} and converts
/// it
/// into a KeY for Solidity AST representation
///
public class SolJSONParser {

    /// keeps track of JSON ids assigned to declarations, required for resolving field references,
    /// types etc.
    /// TODO: what if a type under declaration references itself (is that possible in Solidity?)
    private final HashMap<Integer, Declaration> id2Name = new HashMap<>();

    /// parses the Solidity file found at the provided [URI] and converts it into a
    /// list of [SolidityProgramElement]s of declarations representing the Solidity programs
    /// @param file the URI where to find the Solidity code
    /// @return list of top level declarations (usually contracts) representing the Solidity code
    public List<SolidityProgramElement> parse(URI file) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(file.toURL());
        return json2SolidityAST(root);
    }

    public List<SolidityProgramElement> parse(String contract) throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        JsonNode root = mapper.readTree(contract);
        return json2SolidityAST(root);
    }

    /// convert the JSON AST representation into a KeY for Solidity representation
    /// @param root the root node representing the JSON AST
    /// @return the KeY AST representation of {@code root}
    private List<SolidityProgramElement> json2SolidityAST(JsonNode root) {
        if ("SourceUnit".equals(root.findValue("nodeType").asText())) {
            return parseSourceUnit(root.findValues("nodes"));
        }
        return new ArrayList<>();
    }

    private List<SolidityProgramElement> parseSourceUnit(List<JsonNode> nodes) {
        List<SolidityProgramElement> elements = new ArrayList<>();
        for (var node : nodes) {
            if (node.findValue("contractKind").asText().equals("contract")) {
                elements.add(parseContract(node));
            }
        }
        return elements;
    }


    private ContractDeclaration parseContract(JsonNode contractNode) {
        String contractName = contractNode.findValue("canonicalName").asText(); // there is also a
        // field "name"
        // now retrieve declared fields, functions, structs etc.
        List<StateVariableDeclaration> fields = new ArrayList<>();
        List<FunctionDeclaration> functions = new ArrayList<>();
        List<StructDeclaration> structs = new ArrayList<>();

        for (Iterator<JsonNode> it = contractNode.findValue("nodes").elements(); it.hasNext();) {
            final JsonNode node = it.next();
            final String nodeType = node.findValue("nodeType").asText();
            switch (nodeType) {
                case "VariableDeclaration" -> fields.add(parseVariableField(node));
                case "FunctionDefinition" -> functions.add(parseFunction(node));
                case "StructDefinition" -> structs.add(parseStruct(node));
                default -> throw new RuntimeException("Unknown node type " + nodeType);
            }
        }

        final ContractDeclaration cdecl =
            new ContractDeclaration(new Name(contractName), fields, structs, functions);
        final int contractId = contractNode.findValue("id").asInt();
        id2Name.put(contractId, cdecl);
        return cdecl;
    }

    private StructDeclaration parseStruct(JsonNode structNode) {
        String name = structNode.findValue("name").asText();
        List<FieldDeclaration> fields = structNode.findValue("members").valueStream().map(this::parseField).toList();

        return new StructDeclaration(new Name(name), fields);
    }

    private FieldDeclaration parseField(JsonNode fieldNode) {
        final String fieldName = fieldNode.findValue("name").asText();
        final String fieldType = fieldNode.findValue("typeName").findValue("name").asText();

        return new FieldDeclaration(new Name(fieldName), new TypeReference(new Name(fieldType)));
    }

    private FunctionDeclaration parseFunction(JsonNode node) {
        final String name = node.findValue("name").asText();
        Stream<JsonNode> parameters = node.findValue("returnParameters").findValue("parameters").valueStream();
        List<ParameterDeclaration> returnParameters = parameters.map(this::parseParam).toList();
        List<ParameterDeclaration> inputParamenters =
            node.findValue("parameters").findValue("parameters").valueStream()
                    .map(this::parseParam).toList();

        Block body = parseBlock(node.findValue("body"));
        String kind = node.findValue("kind").asText();
        Visibility visibility = Visibility.fromString(node.findValue("visibility").asText());
        StateMutability stateMutability = StateMutability.valueOf(node.findValue("stateMutability").asText());
        return new FunctionDeclaration(new Name(name), returnParameters, inputParamenters, body, kind, visibility, stateMutability);
    }

    private Block parseBlock(JsonNode jsonBody) {
        // List<JsonNode> statements =
        // if (statements.getFirst().isEmpty()) {
        // return new Block(List.of());
        // }
        List<Statement> blockStatements =
            jsonBody.findValue("statements").valueStream().map(this::parseStatement).toList();
        // statements.stream().map(this::parseStatement).toList();
        return new Block(blockStatements);
    }

    private @NonNull Statement parseStatement(JsonNode statement) {
        String type = statement.findValue("nodeType").asText();
        if(statement.has("expression")) {
            Expression expression = parseExpression(statement.findValue("expression"));
            return switch (type) {
                case "ExpressionStatement" -> new ExpressionStatement(expression);
                case "Return" -> new ReturnStatment(expression);
                default -> throw new RuntimeException("Statement type " + type + " is not supported");
            };
        }
        else if(statement.has("declarations")) {
            List<Declaration> declarations = statement.findValue("declarations").valueStream().map(this::parseDeclaration).toList();
            return new DeclarationStatement(declarations);
        }
        else if(statement.has("condition")){
            Expression condition = parseExpression(statement.findValue("condition"));
            if(type.equals("IfStatement")){
                Statement trueBody = parseStatement(statement.findValue("trueBody"));
                if(!statement.has("falseBody"))
                    return new ConditionStatement(condition, trueBody);
                Statement falseBody = parseStatement(statement.findValue("falseBody"));
                return new ConditionStatement(condition, trueBody, falseBody);

            }
            else if(type.equals("WhileStatement")) {
                Statement body = parseStatement(statement.findValue("body"));
                return new WhileStatement(condition, body);

            }
        }
        else if(statement.has("statements")){
            return parseBlock(statement);
        }
        else if(type.equals("Continue")){
            return new ContinueStatement();
        }
        else if(type.equals("Break")){
            return new BreakStatement();
        }


        return null;
    }

    private Declaration parseDeclaration(JsonNode declaration){
        String nameS = declaration.findValue("name").asText();
        Name name = new Name(nameS);
        String typeName = declaration.findValue("typeName").findValue("nodeType").asText();
        int id = declaration.findValue("id").asInt();
        if(typeName.equals("ArrayTypeName")){
            int length = declaration.findValue("typeName").findValue("length").findValue("value").asInt();
            String struct = declaration.findValue("typeName").findValue("baseType").findValue("name").asText();
            ArrayDeclaration field = new ArrayDeclaration(name, struct, length);
            id2Name.put(id, field);
            return field;
        }
        String struct = declaration.findValue("typeName").findValue("pathNode").findValue("name").asText();
        MemoryDeclaration memDeclaration = new MemoryDeclaration(name, struct);
        id2Name.put(id, memDeclaration);
        return memDeclaration;
    }

    private ParameterDeclaration parseParam(JsonNode node) {
        final String fieldName = node.findValue("name").asText();
        final String fieldType =
            node.findValue("typeDescriptions").findValue("typeString").asText();

        final ParameterDeclaration field =
            new ParameterDeclaration(new Name(fieldName),
                new TypeReference(new Name(fieldType)));
        final int id = node.findValue("id").asInt();
        id2Name.put(id, field);

        return field;
    }

    private StateVariableDeclaration parseVariableField(JsonNode fieldNode) {
        final String fieldName = fieldNode.findValue("name").asText();
        final String fieldType = fieldNode.findValue("typeName").findValue("name").asText();
        // boolean isPrimitive =
        // fieldNode.findValue("typeName").findValue("nodeType").asText().equals("ElementaryTypeName");

        // TODO: Implement modifiers
        String visibility = fieldNode.findValue("visibility").asText();

        JsonNode initializer = fieldNode.findValue("value");
        Expression initializerExp = null;
        if (initializer != null) {
            initializerExp = parseExpression(initializer);
        }

        final StateVariableDeclaration field =
            new StateVariableDeclaration(new Name(fieldName),
                new TypeReference(new Name(fieldType)),
                initializerExp);
        final int id = fieldNode.findValue("id").asInt();
        id2Name.put(id, field);

        return field;
    }

    private Expression parseExpression(JsonNode initializer) {
        final String nodeType = initializer.findValue("nodeType").asText();
        Type expType = getType(initializer.findValue("typeDescriptions").findValue("typeIdentifier").textValue());
        Expression exp = switch (nodeType) {
            case "Literal" -> parseLiteral(expType, initializer);
            case "BinaryOperation" -> parseBinaryOperation(expType, initializer);
            case "UnaryOperation" -> parseUnaryOperation(expType, initializer);
            case "Identifier" -> parseIdentifier(expType, initializer);
            case "Assignment" -> parseAssignment(expType, initializer);
            case "MemberAccess" -> parseMemberAccess(expType, initializer);
            case "IndexAccess" -> parseIndexAccess(expType, initializer);
            case "Conditional" -> parseConditional(expType, initializer);
            case "TupleExpression" -> parseTuple(expType, initializer);
            case "IndexRangeAccess" -> parseIndexRangeAccess(expType, initializer);
            default -> throw new RuntimeException("Not yet supported expression type: " + nodeType);
        };
        return exp;
    }

    private Expression parseIndexRangeAccess(Type expType, JsonNode initializer) {
        Expression baseExp = parseExpression(initializer.findValue("baseExpression"));
        Expression startExp = parseExpression(initializer.findValue("startExpression"));
        Expression endExp = parseExpression(initializer.findValue("endExpression"));
        return new IndexRangeExpression(baseExp, startExp, endExp, expType);
    }

    private Expression parseTuple(Type expType, JsonNode initializer) {
        List<Expression> components = initializer.findValue("components").valueStream().map(this::parseExpression).toList();
        return new TupleExpression(expType, components);
    }

    private Expression parseConditional(Type expType, JsonNode initializer) {
        Expression cond = parseExpression(initializer.findValue("condition"));
        Expression falseExpression = parseExpression(initializer.findValue("falseExpression"));
        Expression trueExpression = parseExpression(initializer.findValue("trueExpression"));

        return new TernaryOperator(expType, cond, falseExpression, trueExpression);
    }

    private Expression parseIndexAccess(Type expType, JsonNode initializer) {
        String leftExp = initializer.findValue("baseExpression").findValue("name").asText();
        Expression indexExp = parseExpression(initializer.findValue("indexExpression"));
        return new IndexExpression(leftExp, indexExp, expType);
    }

    private Expression parseMemberAccess(Type expType, JsonNode initializer) {
        Expression leftExp = parseExpression(initializer.findValue("expression"));
        String rightName = initializer.findValue("memberName").asText();
        return new MemberExp(leftExp, rightName, expType);
    }

    private Expression parseAssignment(Type expType, JsonNode assign) {
        final String op = assign.findValue("operator").asText();
        Expression left = parseExpression(assign.findValue("leftHandSide"));
        Expression right = parseExpression(assign.findValue("rightHandSide"));
        
        return switch (op) {
            case "=" -> new AssignmentExpression(left, right, expType);
            case "|=" -> new OrEqualOperator(left, right, expType);
            case "^=" -> new XorEqualOperator(left, right, expType);
            case "&=" -> new AndEqualOperator(left, right, expType);
            case "<<=" -> new LeftShiftEqualOperator(left, right, expType);
            case ">>=" -> new RightShiftEqualOperator(left, right, expType);
            case ">>>=" -> new LogicalRightShiftEqualOperator(left, right, expType);
            case "+=" -> new PlusEqualOperator(left, right, expType);
            case "-=" -> new MinusEqualOperator(left, right, expType);
            case "*=" -> new MultiplicationEqualOperator(left, right, expType);
            case "/=" -> new DivisionEqualOperator(left, right, expType);
            case "%=" -> new ModEqualOperator(left, right, expType);
            default -> throw new RuntimeException("Assignment: " + op + " not supported");
        };
    }

    private Expression parseUnaryOperation(Type expType, JsonNode initializer) {
        Expression uExp = parseExpression(initializer.findValue("subExpression"));
        final String operator = initializer.findValue("operator").asText();
        boolean prefix = initializer.findValue("prefix").asBoolean();
        return switch (operator) {
            case "++" -> new PlusPlusOperator(uExp, expType, prefix);
            case "--" -> new MinusMinusOperator(uExp, expType, prefix);
            case "~" -> new BitwiseNotOperator(uExp, expType);
            case "!" -> new NotOperator(uExp, expType);
            case "-" -> new NegateOperator(uExp, expType);
            case "delete" -> new DeleteOperator(uExp, expType);
            default -> throw new RuntimeException("Not yet supported binary operation: " + operator);
        };
    }

    private Expression parseBinaryOperation(Type expType, JsonNode initializer) {
        Expression leftExpression = parseExpression(initializer.findValue("leftExpression"));
        Expression rightExpression = parseExpression(initializer.findValue("rightExpression"));

        final String operator = initializer.findValue("operator").asText();
        return switch (operator) {
            case "+" -> new AddOperator(leftExpression, rightExpression, expType);
            case "-" -> new SubtractionOperator(leftExpression, rightExpression, expType);
            case "*" -> new MultiplicationOperator(leftExpression, rightExpression, expType);
            case "/" -> new DivOperator(leftExpression, rightExpression, expType);
            case "%" -> new ModOperator(leftExpression, rightExpression, expType);
            case "^" -> new ExponentialOperator(leftExpression, rightExpression, expType);
            case "&&" -> new AndOperator(leftExpression, rightExpression, expType);
            case "&" -> new BitwiseAndOperator(leftExpression, rightExpression, expType);
            case "||" -> new OrOperator(leftExpression, rightExpression, expType);
            case "|" -> new BitwiseOrOperator(leftExpression, rightExpression, expType);
            case "!=" -> new UnequalOperator(leftExpression, rightExpression, expType);
            case "==" -> new EqualOperator(leftExpression, rightExpression, expType);
            case ">=" -> new GreaterEqualOperator(leftExpression, rightExpression, expType);
            case ">" -> new GreaterOperator(leftExpression, rightExpression, expType);
            case "<=" -> new LessEqualOperator(leftExpression, rightExpression, expType);
            case "<" -> new LessOperator(leftExpression, rightExpression, expType);
            case "<<" -> new LeftShiftOperator(leftExpression, rightExpression, expType);
            case ">>" -> new RightShiftOperator(leftExpression, rightExpression, expType);
            case ">>>" -> new LogicalRightShiftOperator(leftExpression, rightExpression, expType);
            default ->
                throw new RuntimeException("Not yet supported binary operation: " + operator);
        };
    }

    private VariableReference parseIdentifier(Type expType, JsonNode literal) {
        final String name = literal.findValue("name").asText();
        final int referenceDeclarationId = literal.findValue("referencedDeclaration").asInt();
        final String type_str =
            literal.findValue("typeDescriptions").findValue("typeIdentifier").asText();
        final Type type = getType(type_str);

        final Declaration declaration = id2Name.get(referenceDeclarationId);
        return switch (declaration) {
            case StateVariableDeclaration stateVarDeclaration ->
                new StateVariableReference(new Name(name), stateVarDeclaration, type);
            case ParameterDeclaration parameterDeclaration ->
                new ParameterVariableReference(new Name(name), parameterDeclaration, type);
            case ArrayDeclaration arrayDeclaration ->
                    new ArrayReference(new Name(name), arrayDeclaration, type);
            case null -> throw new RuntimeException(
                "Unknown reference declaration " + referenceDeclarationId);
            default -> throw new RuntimeException(
                "Unexpected reference declaration " + declaration + " expected a state variable.");
        };
    }

    private Type getType(String type_str) {

        @NotNull String[] type_parts = type_str.split("\\$");
        String typeS;
        String array_type = "";
        if(type_parts.length == 1){
            type_parts = type_parts[0].split("_");
            if(type_parts.length == 1){
                typeS = type_parts[0];
            }
            else {
                typeS = type_parts[1];
                if(typeS.equals("rational")){
                    typeS = "int";
                }
            }
        }
        else {
            array_type = type_parts[0].substring(2);
            type_parts = type_parts[1].split("_");
            if(type_parts[1].equals("t"))
                typeS = type_parts[2];
            else
                typeS = type_parts[1];
        }

        Type type = switch (typeS) {
            case "int" -> INT;
            case "int8" -> INT8;
            case "int16" -> INT16;
            case "int24" -> INT24;
            case "int32" -> INT32;
            case "int40" -> INT40;
            case "int48" -> INT48;
            case "int56" -> INT56;
            case "int64" -> INT64;
            case "int72" -> INT72;
            case "int80" -> INT80;
            case "int88" -> INT88;
            case "int96" -> INT96;
            case "int104" -> INT104;
            case "int112" -> INT112;
            case "int120" -> INT120;
            case "int128" -> INT128;
            case "int136" -> INT136;
            case "int144" -> INT144;
            case "int152" -> INT152;
            case "int160" -> INT160;
            case "int168" -> INT168;
            case "int176" -> INT176;
            case "int184" -> INT184;
            case "int192" -> INT192;
            case "int200" -> INT200;
            case "int208" -> INT208;
            case "int216" -> INT216;
            case "int224" -> INT224;
            case "int232" -> INT232;
            case "int240" -> INT240;
            case "int248" -> INT248;
            case "int256" -> INT256;

            case "uint" -> UINT;
            case "uint8" -> UINT8;
            case "uint16" -> UINT16;
            case "uint24" -> UINT24;
            case "uint32" -> UINT32;
            case "uint40" -> UINT40;
            case "uint48" -> UINT48;
            case "uint56" -> UINT56;
            case "uint64" -> UINT64;
            case "uint72" -> UINT72;
            case "uint80" -> UINT80;
            case "uint88" -> UINT88;
            case "uint96" -> UINT96;
            case "uint104" -> UINT104;
            case "uint112" -> UINT112;
            case "uint120" -> UINT120;
            case "uint128" -> UINT128;
            case "uint136" -> UINT136;
            case "uint144" -> UINT144;
            case "uint152" -> UINT152;
            case "uint160" -> UINT160;
            case "uint168" -> UINT168;
            case "uint176" -> UINT176;
            case "uint184" -> UINT184;
            case "uint192" -> UINT192;
            case "uint200" -> UINT200;
            case "uint208" -> UINT208;
            case "uint216" -> UINT216;
            case "uint224" -> UINT224;
            case "uint232" -> UINT232;
            case "uint240" -> UINT240;
            case "uint248" -> UINT248;
            case "uint256" -> UINT256;

            case "bytes" -> BYTES;
            case "bytes1" -> BYTES1;
            case "bytes2" -> BYTES2;
            case "bytes3" -> BYTES3;
            case "bytes4" -> BYTES4;
            case "bytes5" -> BYTES5;
            case "bytes6" -> BYTES6;
            case "bytes7" -> BYTES7;
            case "bytes8" -> BYTES8;
            case "bytes9" -> BYTES9;
            case "bytes10" -> BYTES10;
            case "bytes11" -> BYTES11;
            case "bytes12" -> BYTES12;
            case "bytes13" -> BYTES13;
            case "bytes14" -> BYTES14;
            case "bytes15" -> BYTES15;
            case "bytes16" -> BYTES16;
            case "bytes17" -> BYTES17;
            case "bytes18" -> BYTES18;
            case "bytes19" -> BYTES19;
            case "bytes20" -> BYTES20;
            case "bytes21" -> BYTES21;
            case "bytes22" -> BYTES22;
            case "bytes23" -> BYTES23;
            case "bytes24" -> BYTES24;
            case "bytes25" -> BYTES25;
            case "bytes26" -> BYTES26;
            case "bytes27" -> BYTES27;
            case "bytes28" -> BYTES28;
            case "bytes29" -> BYTES29;
            case "bytes30" -> BYTES30;
            case "bytes31" -> BYTES31;
            case "bytes32" -> BYTES32;

            case "bool" -> BOOL;
            case "address" -> ADDRESS;
            case "string" -> STRING;
            case "fixed" -> FIXED;
            case "ufixed" -> UFIXED;
            // TODO: Fix this case
            default -> switch (array_type) {
                case "struct" -> STRUCT;
                default -> throw new RuntimeException();
            };
        };
        return type;
    }

    private Literal parseLiteral(Type expType, JsonNode literal) {
        final String kind = literal.findValue("kind").asText();
        return switch (kind) {
            case "number" -> {
                String initializerExp = literal.findValue("value").asText();
                yield new Uint256Literal(BigIntegerParser.parseWithFastParser(initializerExp));
            }
            case "bool" -> {
                String initializerExp = literal.findValue("value").asText();
                yield initializerExp.equals("true") ? BoolLiteral.TRUE : BoolLiteral.FALSE;
            }
            // FIX!!!!
            default -> throw new RuntimeException("Not yet supported literal");
        };
    }
}
